config/routes.rb
Rails.application.routes.draw do
  resources :user_in_outs
  root to: 'assistance#home'
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # associations
  has_many :user_in_out
  # validations
  validates_presence_of :admin
end

app/models/user_in_out.rb
class UserInOut < ApplicationRecord
  # associations
  belongs_to :user

  # validations
  validates_presence_of :user_in, :user_out
  validate :user_out_must_be_greater_than_user_in

  def user_out_must_be_greater_than_user_in
    if user_in != nil && user_out != nil && user_in >= user_out
      errors.add(:user_in, "user_in can't be greater or equal than user_out")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assistance_controller.rb
class AssistanceController < ApplicationController
  def home
  end
end

app/controllers/user_in_outs_controller.rb
class UserInOutsController < ApplicationController
  before_action :set_user_in_out, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /user_in_outs
  # GET /user_in_outs.json
  def index
    if current_user.admin
      @user_in_outs = UserInOut.all
    else
      @user_in_outs = UserInOut.where(user_id: current_user.id ) 
    end
  end

  # GET /user_in_outs/1
  # GET /user_in_outs/1.json
  def show
  end

  # GET /user_in_outs/new
  def new
    @user_in_out = UserInOut.new
  end

  # GET /user_in_outs/1/edit
  def edit
  end

  # POST /user_in_outs
  # POST /user_in_outs.json
  def create
    @user_in_out = UserInOut.new(user_in_out_params)
    @user_in_out.user = current_user

    respond_to do |format|
      if @user_in_out.save
        format.html { redirect_to @user_in_out, notice: 'User in out was successfully created.' }
        format.json { render :show, status: :created, location: @user_in_out }
      else
        format.html { render :new }
        format.json { render json: @user_in_out.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_in_outs/1
  # PATCH/PUT /user_in_outs/1.json
  def update
    respond_to do |format|
      if @user_in_out.update(user_in_out_params)
        format.html { redirect_to @user_in_out, notice: 'User in out was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_in_out }
      else
        format.html { render :edit }
        format.json { render json: @user_in_out.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_in_outs/1
  # DELETE /user_in_outs/1.json
  def destroy
    @user_in_out.destroy
    respond_to do |format|
      format.html { redirect_to user_in_outs_url, notice: 'User in out was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_in_out
      @user_in_out = UserInOut.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_in_out_params
      params.require(:user_in_out).permit(:user_in, :user_out)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistance_helper.rb
module AssistanceHelper
end

app/helpers/user_in_outs_helper.rb
module UserInOutsHelper
end

app/views/assistance/home.html.erb
<div class="center jumbotron">

  <h1>Welcome to the Check in/Check out application</h1>

  <% if current_user && current_user.admin %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-lg btn-primary" %>
    <%= link_to 'User In/Out', new_user_in_out_path, class:"btn btn-lg btn-primary" %>
  <% elsif current_user && !current_user.admin %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-lg btn-primary" %>
    <%= link_to 'My In/out', user_in_outs_path, class: "btn btn-lg btn-primary" %>
  <% else %>
    <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-lg btn-primary" %>
    <%= link_to 'Sign in', new_user_session_path, class: "btn btn-lg btn-primary" %>
  <% end %>

</div>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <div class="container">
      <%= render "layouts/alerts" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/user_in_outs/_form.html.erb
<%= form_with(model: user_in_out, local: true) do |form| %>
  <% if user_in_out.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_in_out.errors.count, "error") %> prohibited this user_in_out from being saved:</h2>

      <ul>
      <% user_in_out.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <div class="field">
        <tr>
          <td><%= form.label :user_in %></td>
          <td><%= form.time_select :user_in, value: DateTime.now.in_time_zone.strftime("%F at %I:%M%p") %></td>
        </tr>
    </div>

    <div class="field">
        <tr>
            <td><%= form.label :user_out %></td>
            <td><%= form.time_select :user_out, value: DateTime.now.in_time_zone.strftime("%F at %I:%M%p") %></td>
        </tr>
    </div>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_in_outs/edit.html.erb
<h1>Editing User In Out</h1>

<%= render 'form', user_in_out: @user_in_out %>

<%= link_to 'Show', @user_in_out %> |
<%= link_to 'Back', user_in_outs_path %>

app/views/user_in_outs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User check-in check-out list</h1>

<table>
  <thead>
    <tr>
      <th>User in</th>
      <th>User out</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_in_outs.each do |user_in_out| %>
      <tr>
        <td><%= user_in_out.user_in %>&nbsp&nbsp</td>
        <td><%= user_in_out.user_out %>&nbsp&nbsp</td>
        <td><%= user_in_out.user.email %>&nbsp&nbsp</td>
        <% if current_user && current_user.admin %>
          <td><%= link_to 'Edit', edit_user_in_out_path(user_in_out) %></td>
          <td><%= link_to 'Destroy', user_in_out, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin %>
  <%= link_to 'New User Check-in Check-out', new_user_in_out_path, class:"btn btn-lg btn-primary" %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"btn btn-lg btn-primary" %>
<% else %>
  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"btn btn-lg btn-primary" %>
<% end %>

app/views/user_in_outs/new.html.erb
<h1>New User In/Out</h1>

<%= render 'form', user_in_out: @user_in_out %>

<%= link_to 'Back', user_in_outs_path %>

app/views/user_in_outs/show.html.erb
<tr>
  <td>
    <strong>User in:</strong>
    <%= @user_in_out.user_in.strftime("%F at %I:%M%p") %>
  </td>
  &nbsp
  <td>
    <strong>User out:</strong>
    <%= @user_in_out.user_out.strftime("%F at %I:%M%p") %>
  </<td>
  &nbsp
  <td>
    <strong>User:</strong>
    <%= @user_in_out.user.email %>
  </td>
  &nbsp
</tr>

<%= link_to 'Edit', edit_user_in_out_path(@user_in_out) %> |
<%= link_to 'Back', user_in_outs_path %>